### ISSUE TITLE
RECHNUNGEN: Postfinance als PaymentProvider hinterlegen

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito#1334]
Es sollen die Parameter für EBICS-Verbindungen zu bekannten Banken hinterlegt werden, um Eingabefehler zu vermeiden und definitiven Support für verschiedene Banken zu signalisieren. 

Im ersten Schritt werden nur die Daten der Postfinance hinterlegt

In `config/settings.yml` 

```yaml
payment_providers:
  - name: postfinance
    url: 
    host_id:
    encryption_hash:
    authentication_hash:
```

https://www.postfinance.ch/content/dam/pfch/doc/460_479/479_06_de.pdf

# Tech-Spec

- [ ] config anlegen
- [ ] Auslesen sicherstellen
