### ISSUE TITLE
Export: Spaltenauswahl Teilnehmerexport funktioniert mitunter nicht

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito#3353]
Folgender Export job bei PBS beispielsweise läuft nicht 

```
--- !ruby/object:Export::EventParticipationsExportJob
locale: de
format: :xlsx
exporter:
user_id: 25881
options: !ruby/object:ActionController::Parameters
  parameters: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    filter: participants
    selection: 'true'
    controller: event/participations
    action: index
    locale: de
    group_id: '301'
    event_id: '28323'
    format: xlsx
    filename: event_participation_export_1746178993-25881
  permitted: false
filter: !ruby/object:Event::ParticipationFilter
  event_id: 28323
  user_id: 25881
  params: !ruby/object:ActionController::Parameters
    parameters: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
      filter: participants
      selection: 'true'
      controller: event/participations
      action: index
      locale: de
      group_id: '301'
      event_id: '28323'
      format: xlsx
    permitted: false
group_id: 301
```

Für weitere Events siehe https://sentry.puzzle.ch/pitc/hitobito-backend/issues/75575/
