### ISSUE TITLE
Export: Spaltenauswahl Subscriber funktioniert mitunter nicht

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito#3355]
Folgender Export job bei PBS beispielsweise läuft nicht

```
--- !ruby/object:Export::SubscriptionsJob
locale: de
format: :xlsx
exporter:
user_id: 78030
options: !ruby/object:ActionController::Parameters
  parameters: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    selection: 'true'
    filename: subscriptions_4160_1746087677-78030
  permitted: false
mailing_list_id: 4160
```

siehe https://sentry.puzzle.ch/pitc/hitobito-backend/issues/75993/
