### ISSUE TITLE
ELTERNZUGANG: Verwaltete Person wurde nicht per ID übergeben

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito#3394]
Sentry: https://sentry.puzzle.ch/pitc/hitobito-backend/issues/74197
Exception: ActiveRecord::NotNullViolation
Action: Person::ManagedsController#create
Messages:

- ActiveRecord::NotNullViolation
- PG::NotNullViolation: 
- ERROR:  null value in column "managed_id" of relation "people_managers" violates not-null constraint
- DETAIL:  Failing row contains (FIRST_ID, SECOND_ID, null, TIMESTAMP, TIMESTAMP).
- The values for FIRST_ID, SECOND_ID and TIMESTAMP seem valid. Details in Sentry.

Params:

```yaml
{
  action: create, 
  authenticity_token: [Filtered], 
  button: , 
  controller: person/manageds, 
  people_manager: {
    managed: Torbem, 
    managed_id: 
  },
  person_id: SECOND_ID
}
```
The Name of the Managed Person has been changed, see Sentry for details.
